"""MarginEdge Public API pull.

API: https://api.marginedge.com/public  (read-only, x-api-key header, opaque `nextPage` cursor)
Docs: https://developer.marginedge.com  (key is generated by a MarginEdge Admin user, one key per user)

Datasets pulled per restaurant unit:
  restaurantUnits          -> raw/marginedge/_all/restaurantUnits/units.json
  categories, vendors,
  products                 -> raw/marginedge/<loc>/<dataset>/all.json   (full refresh each run; small)
  orders (list)            -> raw/marginedge/<loc>/orders/<start>_<end>.json
  orders/{id} (detail)     -> raw/marginedge/<loc>/orderDetail/<orderId>.json  (only for orders not yet detailed)

Count sheets / inventories, sales reports and P&L are listed in MarginEdge's help article but were not in
the published OpenAPI at build time; `pull_inventories()` is a guarded stub with the path configurable via
MARGINEDGE_INVENTORY_PATH so it can be switched on without a code change once the path is confirmed.
"""
from __future__ import annotations

from datetime import date, timedelta

from .util import Http, env, iso, log, settings, today_local, write_raw

HDR = "x-api-key"


class MarginEdge:
    def __init__(self, api_key: str | None = None, base_url: str | None = None):
        cfg = settings()["marginedge"]
        self.key = api_key or env("MARGINEDGE_API_KEY", required=True)
        self.http = Http(base_url or cfg["base_url"], headers={HDR: self.key, "Accept": "application/json"}, rps=4)

    # ---- low level -------------------------------------------------------------------------
    def _paged(self, path: str, params: dict, list_key: str):
        """Follow the opaque nextPage cursor until exhausted; yields items."""
        params = dict(params)
        while True:
            j = self.http.get(path, params=params).json()
            for it in j.get(list_key, []) or []:
                yield it
            nxt = j.get("nextPage")
            if not nxt:
                break
            params["nextPage"] = nxt

    # ---- datasets --------------------------------------------------------------------------
    def restaurant_units(self) -> list[dict]:
        return self.http.get("/restaurantUnits").json().get("restaurants", [])

    def categories(self, unit_id: str) -> list[dict]:
        return list(self._paged("/categories", {"restaurantUnitId": unit_id}, "categories"))

    def vendors(self, unit_id: str) -> list[dict]:
        return list(self._paged("/vendors", {"restaurantUnitId": unit_id}, "vendors"))

    def products(self, unit_id: str) -> list[dict]:
        return list(self._paged("/products", {"restaurantUnitId": unit_id}, "products"))

    def orders(self, unit_id: str, start: date, end: date, status: str | None = None) -> list[dict]:
        p = {"restaurantUnitId": unit_id, "startDate": iso(start), "endDate": iso(end)}
        if status and status != "ALL":
            p["orderStatus"] = status
        return list(self._paged("/orders", p, "orders"))

    def order_detail(self, unit_id: str, order_id: str) -> dict:
        return self.http.get(f"/orders/{order_id}", params={"restaurantUnitId": unit_id}).json()

    def inventories(self, unit_id: str, start: date, end: date) -> list[dict] | None:
        path = env("MARGINEDGE_INVENTORY_PATH")  # e.g. "/inventories" once confirmed in the developer portal
        if not path:
            return None
        return list(self._paged(path, {"restaurantUnitId": unit_id, "startDate": iso(start), "endDate": iso(end)}, "inventories"))


# ---- orchestration ------------------------------------------------------------------------

def pull(locations: list[dict], days_back: int, detailed_ids: set[tuple[str, str]] | None = None) -> dict:
    """Pull everything for the given locations. Returns a summary dict for pull_log."""
    me = MarginEdge()
    detailed_ids = detailed_ids or set()
    end = today_local()
    start = end - timedelta(days=days_back)
    summary = {}

    units = me.restaurant_units()
    write_raw("marginedge", "_all", "restaurantUnits", "units", {"restaurants": units})
    log.info("MarginEdge: %d restaurant units visible to this key: %s", len(units), ", ".join(f"{u.get('id')}={u.get('name')}" for u in units))

    for loc in locations:
        uid = str(loc.get("marginedge_unit_id") or "").strip()
        if not uid:
            log.warning("MarginEdge: %s has no marginedge_unit_id in config/locations.json — skipped", loc["slug"])
            continue
        slug = loc["slug"]
        cats = me.categories(uid); write_raw("marginedge", slug, "categories", "all", {"categories": cats})
        vends = me.vendors(uid);   write_raw("marginedge", slug, "vendors", "all", {"vendors": vends})
        prods = me.products(uid);  write_raw("marginedge", slug, "products", "all", {"products": prods})
        orders = me.orders(uid, start, end)
        write_raw("marginedge", slug, "orders", f"{iso(start)}_{iso(end)}", {"orders": orders, "window": [iso(start), iso(end)]})
        n_detail = 0
        for o in orders:
            oid = str(o.get("orderId"))
            if (slug, oid) in detailed_ids and o.get("status") not in ("PENDING", "REVIEW", "IN_REVIEW"):
                continue  # already have detail and it is final
            write_raw("marginedge", slug, "orderDetail", oid, me.order_detail(uid, oid))
            n_detail += 1
        inv = me.inventories(uid, start, end)
        if inv is not None:
            write_raw("marginedge", slug, "inventories", f"{iso(start)}_{iso(end)}", {"inventories": inv})
        summary[slug] = {"categories": len(cats), "vendors": len(vends), "products": len(prods), "orders": len(orders), "order_details": n_detail, "window": [iso(start), iso(end)]}
        log.info("MarginEdge %s: %s", slug, summary[slug])
    return summary
